name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=80

  build-and-deploy:
    runs-on: self-hosted
    needs: test   # only runs if tests succeed
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t flask-frontend:staging .

      - name: Run container
        run: |
          # stop old container if it exists
          docker ps -q --filter "name=flask-frontend-staging" | grep -q . && docker rm -f flask-frontend-staging
          # run new container on port 5001 -> 5000
          docker run -d -p 5001:5000 --name flask-frontend-staging flask-frontend:staging
