name: Deploy Flask Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old container
        run: docker rm -f flask-frontend || true

      - name: Build Docker image
        run: docker build -t flask-frontend:latest .

      - name: Run container
        run: |
          docker run -d \
            --name flask-frontend \
            -p 5000:5000 \
            flask-frontend:latest
